// <auto-generated />
using KiemTraGiuaKi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiemTraGiuaKi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KiemTraGiuaKi.Models.DishCategory_BIT242377", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DishCategories_BIT242377", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các món ăn mặn",
                            Name = "Món mặn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các món ăn chay",
                            Name = "Món chay"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Các món tráng miệng",
                            Name = "Tráng miệng"
                        });
                });

            modelBuilder.Entity("KiemTraGiuaKi.Models.DishImage_BIT242377", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.ToTable("DishImages_BIT242377", (string)null);
                });

            modelBuilder.Entity("KiemTraGiuaKi.Models.Dish_BIT242377", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DishCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DishCategoryId");

                    b.HasIndex("Name", "DishCategoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_Dish_Name_CategoryId");

                    b.ToTable("Dishes_BIT242377", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phở bò truyền thống",
                            DishCategoryId = 1,
                            IsAvailable = true,
                            Name = "Phở bò",
                            PreparationTime = 15,
                            Price = 45000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bánh xèo giòn tan",
                            DishCategoryId = 1,
                            IsAvailable = true,
                            Name = "Bánh xèo",
                            PreparationTime = 20,
                            Price = 35000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cà tím nấu chay",
                            DishCategoryId = 2,
                            IsAvailable = true,
                            Name = "Cà tím luộc",
                            PreparationTime = 10,
                            Price = 20000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Canh rau cải ngọt",
                            DishCategoryId = 2,
                            IsAvailable = true,
                            Name = "Canh rau cải",
                            PreparationTime = 8,
                            Price = 25000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chè đậu đỏ ngọt ngào",
                            DishCategoryId = 3,
                            IsAvailable = true,
                            Name = "Chè đậu đỏ",
                            PreparationTime = 25,
                            Price = 15000m
                        });
                });

            modelBuilder.Entity("KiemTraGiuaKi.Models.DishImage_BIT242377", b =>
                {
                    b.HasOne("KiemTraGiuaKi.Models.Dish_BIT242377", "Dish")
                        .WithMany("DishImages")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("KiemTraGiuaKi.Models.Dish_BIT242377", b =>
                {
                    b.HasOne("KiemTraGiuaKi.Models.DishCategory_BIT242377", "DishCategory")
                        .WithMany("Dishes")
                        .HasForeignKey("DishCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DishCategory");
                });

            modelBuilder.Entity("KiemTraGiuaKi.Models.DishCategory_BIT242377", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("KiemTraGiuaKi.Models.Dish_BIT242377", b =>
                {
                    b.Navigation("DishImages");
                });
#pragma warning restore 612, 618
        }
    }
}
